"""Generic Janitza 19xxx register catalogue."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    UnitOfApparentPower,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfReactivePower,
)


@dataclass(frozen=True, kw_only=True)
class JanitzaRegister:
    """Description of a single Janitza 32-bit float register."""

    key: str
    address: int
    name: str
    native_unit_of_measurement: str | None
    device_class: SensorDeviceClass | None
    state_class: SensorStateClass
    suggested_display_precision: int | None = 2
    entity_registry_enabled_default: bool = True


REGISTERS: tuple[JanitzaRegister, ...] = (
    JanitzaRegister(
        key="voltage_l1_n",
        address=19000,
        name="Voltage L1-N",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_l2_n",
        address=19002,
        name="Voltage L2-N",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_l3_n",
        address=19004,
        name="Voltage L3-N",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_l1_l2",
        address=19006,
        name="Voltage L1-L2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_l2_l3",
        address=19008,
        name="Voltage L2-L3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_l3_l1",
        address=19010,
        name="Voltage L3-L1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_l1",
        address=19012,
        name="Current L1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_l2",
        address=19014,
        name="Current L2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_l3",
        address=19016,
        name="Current L3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_sum",
        address=19018,
        name="Current vector sum",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="active_power_l1",
        address=19020,
        name="Active power L1",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="active_power_l2",
        address=19022,
        name="Active power L2",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="active_power_l3",
        address=19024,
        name="Active power L3",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="active_power_total",
        address=19026,
        name="Active power total",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="apparent_power_l1",
        address=19028,
        name="Apparent power L1",
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="apparent_power_l2",
        address=19030,
        name="Apparent power L2",
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="apparent_power_l3",
        address=19032,
        name="Apparent power L3",
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="apparent_power_total",
        address=19034,
        name="Apparent power total",
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="reactive_power_l1",
        address=19036,
        name="Reactive power L1",
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="reactive_power_l2",
        address=19038,
        name="Reactive power L2",
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="reactive_power_l3",
        address=19040,
        name="Reactive power L3",
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="reactive_power_total",
        address=19042,
        name="Reactive power total",
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="power_factor_l1",
        address=19044,
        name="Power factor L1",
        native_unit_of_measurement=None,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=3,
    ),
    JanitzaRegister(
        key="power_factor_l2",
        address=19046,
        name="Power factor L2",
        native_unit_of_measurement=None,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=3,
    ),
    JanitzaRegister(
        key="power_factor_l3",
        address=19048,
        name="Power factor L3",
        native_unit_of_measurement=None,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=3,
    ),
    JanitzaRegister(
        key="frequency",
        address=19050,
        name="Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="active_energy_total",
        address=19060,
        name="Active energy",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_consumed_total",
        address=19068,
        name="Active energy consumed total",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_consumed_l1",
        address=19062,
        name="Active energy consumed L1",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_consumed_l2",
        address=19064,
        name="Active energy consumed L2",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_consumed_l3",
        address=19066,
        name="Active energy consumed L3",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_delivered_total",
        address=19076,
        name="Active energy delivered total",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_delivered_l1",
        address=19070,
        name="Active energy delivered L1",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_delivered_l2",
        address=19072,
        name="Active energy delivered L2",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="active_energy_delivered_l3",
        address=19074,
        name="Active energy delivered L3",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="apparent_energy_total",
        address=19084,
        name="Apparent energy total",
        native_unit_of_measurement="VAh",
        device_class=None,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="apparent_energy_l1",
        address=19078,
        name="Apparent energy L1",
        native_unit_of_measurement="VAh",
        device_class=None,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="apparent_energy_l2",
        address=19080,
        name="Apparent energy L2",
        native_unit_of_measurement="VAh",
        device_class=None,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="apparent_energy_l3",
        address=19082,
        name="Apparent energy L3",
        native_unit_of_measurement="VAh",
        device_class=None,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_total",
        address=19092,
        name="Reactive energy total",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_inductive_total",
        address=19100,
        name="Reactive energy inductive total",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_inductive_l1",
        address=19094,
        name="Reactive energy inductive L1",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_inductive_l2",
        address=19096,
        name="Reactive energy inductive L2",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_inductive_l3",
        address=19098,
        name="Reactive energy inductive L3",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_capacitive_total",
        address=19108,
        name="Reactive energy capacitive total",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_capacitive_l1",
        address=19102,
        name="Reactive energy capacitive L1",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_capacitive_l2",
        address=19104,
        name="Reactive energy capacitive L2",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="reactive_energy_capacitive_l3",
        address=19106,
        name="Reactive energy capacitive L3",
        native_unit_of_measurement="varh",
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    JanitzaRegister(
        key="voltage_thd_l1_n",
        address=19110,
        name="Voltage THD L1-N",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_thd_l2_n",
        address=19112,
        name="Voltage THD L2-N",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="voltage_thd_l3_n",
        address=19114,
        name="Voltage THD L3-N",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_thd_l1",
        address=19116,
        name="Current THD L1",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_thd_l2",
        address=19118,
        name="Current THD L2",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    JanitzaRegister(
        key="current_thd_l3",
        address=19120,
        name="Current THD L3",
        native_unit_of_measurement="%",
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
    ),
)

MIN_REGISTER_ADDRESS = min(register.address for register in REGISTERS)
MAX_REGISTER_ADDRESS = max(register.address for register in REGISTERS)
